public class Main {
    public static void main(String[] args) {
        System.out.println("Задание 1");
        var dog = 8.0;
        var cat = 3.6;
        var paper = 763789;
        System.out.println("var dog = " + dog);
        System.out.println("var cat = " + cat);
        System.out.println("var paper = " + paper);
        System.out.println("Задание 2");
        dog = dog + 4;
        cat = cat + 4;
        paper = paper + 4;
        System.out.println("dog + 4 = " + dog);
        System.out.println("cat + 4 = " + cat);
        System.out.println("paper + 4 = " + paper);
        System.out.println("Задание 3");
        dog = dog - 3.5;
        cat = cat - 1.6;
        paper = paper - 7639;
        System.out.println("dog - 3.5 = " + dog);
        System.out.println("cat - 1.6 = " + cat);
        System.out.println("paper - 7639 = " + paper);
        System.out.println("Задание 4");
        var friend = 19;
        System.out.println("var friend = " + friend);
        friend = friend + 2;
        System.out.println("friend + 2 = " + friend);
        friend = friend / 7;
        System.out.println("friend / 7 = " + friend);
    System.out.println("Задание 5");
    var frog = 3.5;
    System.out.println("var frog = " + frog);
    frog = frog * 10;
    System.out.println("frog * 10 = " + frog);
    frog = frog / 3.5;
    System.out.println("frog / 3.5 = " + frog);
    frog = frog + 4;
    System.out.println("frog + 4 = " + frog);
    System.out.println("Задание 6");
    var weightOneBoxer = 78.2;
    var weightTwoBoxer = 82.7;
    var totalWeightBoxers = weightOneBoxer + weightTwoBoxer;
    System.out.println("Общая масса двух бойцов: " + totalWeightBoxers + " кг");
    var weightDifference = weightTwoBoxer - weightOneBoxer;
    System.out.println("Разница между массами бойцов: " + weightDifference + " кг");
    System.out.println("Задание 7");
    var remainderOfDivision = weightTwoBoxer % weightOneBoxer;
    System.out.println("Остаток от деления между двумя весами бойцов: " + remainderOfDivision);
    System.out.println("Задание 8");
    var workHours = 640;
    var workHoursOfOneEmployee = 8;
    var quantityOfEmployees = 640 / 8;
    System.out.println("Всего работников в компании — " + quantityOfEmployees + " человек");
    quantityOfEmployees = quantityOfEmployees + 94;
    workHours = workHoursOfOneEmployee * quantityOfEmployees;
    System.out.println("Если в компании работает " + quantityOfEmployees + " человек, то всего " + workHours + " часов работы может быть поделено между сотрудниками");
    }
}